Задание 2. Добавлен README
gpb-it-factory/satvaldiev-telegram-bot pull request #2
Opened 2024-05-06 12:25 UTC by Sergey110123

2024-05-06 17:22 UTC, vaganov-vadim requested changes
Есть пара комментариев по README и .idea, прошу поправить :)

2024-05-06 17:22 UTC, vaganov-vadim commented on README.md
> +skinparam backgroundColor #EEEBDC
Креативная цветовая схема, круто =)

2024-05-06 17:22 UTC, vaganov-vadim commented on README.md
> +Frontend -> Middle: HTTP
Кажется, не хватает самого клиента, он как-то должен инициировать всю цепочку взаимодействий.

2024-05-06 17:22 UTC, vaganov-vadim commented on README.md
> +# Telegram-бот
Не по этому файлу, но в целом - коммитить .idea в репозиторий не нужно, т. к. это файлы твоей IDE, лучше эту папку внести в .gitignore.

2024-05-06 18:24 UTC, Sergey110123 commented on README.md
> +# Telegram-бот
Все понятно, замечания отработаю. Нужно ли мне для этого закрывать текущий PR и затем открывать новый?

2024-05-07 14:32 UTC, vaganov-vadim commented on .gitignore
> +.idea/modules.xml
Жесть какая :) В целом можно просто .idea, вся папка в репозитории не нужна. Но это просто комментарий, не блокер.

2024-05-07 14:33 UTC, vaganov-vadim commented on .gitignore
> +.DS_Store
А вот это очень важно! А то задолбаешься его из репозитория удалять :D

2024-05-07 14:33 UTC, vaganov-vadim approved these changes
Аппрув.

2024-05-07 19:08 UTC, Sergey110123 commented
Мне теперь нужно нажать "Merge when ready" и закрыть PR?

2024-05-08 04:58 UTC, vaganov-vadim commented
Всё так, жми Merge и PR сам закроется.

2024-05-08 05:59 UTC, merged